language: node_js
os: linux
node_js:
  - 12
  - 14

# Build Packages and Storybook
script:
  - npm run bootstrap
  - npm run build
  - npm run storybook:build -- --quiet
  # Publish storybook to Chromatic https://www.chromatic.com/
  - if [[ $TRAVIS_EVENT_TYPE != 'pull_request' ||  $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]]; then npm run chromatic -- --exit-zero-on-changes; fi

# Prevent Github Pages from using Jekyll
before_deploy:
  - touch docs/.nojekyll

after_success:
  - git config --global user.email ${GIT_COMMITTER_EMAIL}
  - git config --global user.name stencila-ci
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" > /dev/null 2>&1
  - git checkout master
  - git checkout .
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  # Deploy a new version of NPM packages and create a Github releases
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: npx lerna publish --yes

  # Deploy a pre-release candidates from `next` branch
  - provider: script
    skip_cleanup: true
    on:
      branch: next
    script: npx lerna publish --yes --canary --preid next --dist-tag next

  # Deploy Storybook to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master
